const palette = {
  amber: "#D4822A",
  amberLight: "#E8A855",
  amberDark: "#A8601A",
  forest: "#2D5A27",
  forestLight: "#4A8A42",
  forestMid: "#3B7034",
  sage: "#7A9E7E",
  sageMist: "#B8D4BC",
  cream: "#F7F2EA",
  creamDark: "#EDE5D8",
  bark: "#5C3D2E",
  barkLight: "#8B6355",
  earth: "#1A1208",
  sand: "#C9B99A",
  sandLight: "#E8DDD0",
  white: "#FFFFFF",
  offWhite: "#FAFAF7",
  glass: "rgba(255,255,255,0.12)",
  glassDark: "rgba(0,0,0,0.25)",
  overlay: "rgba(26,18,8,0.55)",
  success: "#4CAF50",
  warning: "#FF9800",
  error: "#E53935",
  cardBorder: "rgba(92,61,46,0.12)",
};

export default {
  light: {
    text: palette.earth,
    textSecondary: palette.barkLight,
    textMuted: palette.sand,
    background: palette.cream,
    backgroundSecondary: palette.creamDark,
    surface: palette.white,
    surfaceElevated: palette.offWhite,
    tint: palette.amber,
    tintDark: palette.amberDark,
    tintLight: palette.amberLight,
    accent: palette.forest,
    accentLight: palette.forestLight,
    accentMid: palette.forestMid,
    sage: palette.sage,
    sageMist: palette.sageMist,
    sand: palette.sand,
    sandLight: palette.sandLight,
    bark: palette.bark,
    tabIconDefault: palette.sand,
    tabIconSelected: palette.amber,
    cardBorder: palette.cardBorder,
    glass: palette.glass,
    glassDark: palette.glassDark,
    overlay: palette.overlay,
    success: palette.success,
    warning: palette.warning,
    error: palette.error,
  },
};

export type ColorScheme = typeof palette;
